// Copyright (c) Lauri Mäkinen 2014 - 2015
// All rights reserved.
#define PROPELLER_PACKAGE_IDENTIFIER "PROPELLERPACKAGE"
#define PROPELLER_PACKAGE_IDENTIFIER_SIZE 16
#define PROPELLER_PACKAGE_VERSION_ID 1